# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Publish

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --verbosity normal
    - name: Add Nuget Source
      run: run dotnet nuget add source "https://nuget.pkg.github.com/Takasaki-Studio/Lina/index.json" --username "${{ secrets.USERNAME }}" --password "${{ secrets.SECRET }}" --store-password-in-clear-text --name "github" 